[package]
name = "uuid"
version = "0.1.0"
authors = ["Pavel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }

[profile.release]
opt-level = 3